### ISSUE TITLE
Docker images on ubuntu/python

### ISSUE THREAD

**Issue by xsacha** [canonical/chiselled-python#21]
The images provided on the ubuntu/python dockerhub are all the same python 3.8 images. It is my understanding they should be the version on the tag instead.
Cross-post: https://bugs.launchpad.net/ubuntu-docker-images/+bug/2069652

**Comment by cjdcordeiro** [comment]
Hi @xsacha 

Thanks for reporting it. We're aware of it and will be fixing it over the coming days

**Comment by xsacha** [comment]
Thanks. It is all working now.
